### PR TITLE
Fix issue where `enumNamespaces` rule wouldn't be applied following import statement

### LINKED ISSUE #1569: enumNamespaces ignored when located after an import
# Describe the bug
`enumNamespaces` rule seems to be ignored if the class/struct is at specific position.
Here is some source code, before and after swiftformat run with enumNamespaces rule enabled:

<table>
<tr>
<th> Before </th>
<th> After </th>
</tr>
<tr>
<td>

```swift
import Foundation

final class MyViewModel {
    static let = "A"
}

final class MyViewModel2 {
    static let = "A"
}
```

</td>
<td>

```swift
import Foundation

final class MyViewModel {
    static let = "A"
}

enum MyViewModel2 {
    static let = "A"
}
```

</td>
</tr>
</table>

<table>
<tr>
<th> Before </th>
<th> After </th>
</tr>
<tr>
<td>

```swift
final class  MyViewModel {
    static let = "A"
}

import Foundation

final class MyViewModel2 {
    static let = "A"
}
```

</td>
<td>

```swift
enum MyViewModel {
    static let = "A"
}

import Foundation

final class MyViewModel2 {
    static let = "A"
}
```

</td>
</tr>
</table>

<table>
<tr>
<th> Before </th>
<th> After </th>
</tr>
<tr>
<td>

```swift
final class MyViewModel {
    static let = "A"
}

final class MyViewModel2 {
    static let = "A"
}

import Foundation
```

</td>
<td>

```swift
enum MyViewModel {
    static let = "A"
}

enum MyViewModel2 {
    static let = "A"
}

import Foundation
```

</td>
</tr>
</table>

`import` seems to have a side effect on the following entity.

# Environment
_swiftformat version_: 0.52.8
_swiftformat configuration file_:
```
--lineaftermarks true
--typeblanklines remove
--allman false
--emptybraces no-space
--enumnamespaces always
--asynccapturing
--patternlet hoist
--throwcapturing
--modifierorder
--someAny false
--self insert
--redundanttype inferred
--closurevoid remove
--semicolons never
--importgrouping alpha
--operatorfunc spaced
--nospaceoperators
--ranges spaced
--trailingclosures
--nevertrailing
--commas inline
--trimwhitespace always
--shortoptionals always
--stripunusedargs always
--voidtype void
--yodaswap always
--elseposition same-line
--guardelse auto
--indent 4
--smarttabs enabled
--indentcase true
--ifdef indent
--indentstrings false
--decimalgrouping 3,6
--binarygrouping 4,8
--octalgrouping 4,8
--hexgrouping 4,8
--fractiongrouping disabled
--exponentgrouping disabled
--hexliteralcase uppercase
--exponentcase uppercase
--operatorfunc spaced
--maxwidth none
--assetliterals visual-width
--wraparguments before-first
--wrapparameters before-first
--wrapcollections before-first
--closingparen balanced
--wrapreturntype preserve
--wrapconditions preserve
--wrapeffects preserve
--funcattributes preserve
--typeattributes preserve
--varattributes preserve
--conflictmarkers reject
--extensionmark "MARK: - %t + %c"
--fragment false
--groupedextension "MARK: %c"
--linebreaks lf
--nowrapoperators
--swiftversion 5.8
--selfrequired
--tabwidth unspecified
--typemark "MARK: - %t"
--wrapternary default
--wraptypealiases preserve
--xcodeindentation disabled
--enable andOperator, anyObjectProtocol, assertionFailures, blankLineAfterImports, blankLinesAtEndOfScope, blankLinesBetweenScopes, blockComments, conditionalAssignment, consecutiveBlankLines, consecutiveSpaces, docComments, duplicateImports, initCoderUnavailable, leadingDelimiters, preferKeyPath, redundantBackticks, redundantBreak, redundantClosure, redundantExtensionACL, redundantFileprivate, redundantGet, redundantInit, redundantLet, redundantLetError, redundantNilInit, redundantObjc, redundantOptionalBinding, redundantParens, redundantPattern, spaceAroundBraces, spaceAroundBrackets, spaceAroundComments, spaceAroundGenerics, spaceAroundParens, spaceInsideBraces, spaceInsideBrackets, spaceInsideComments, spaceInsideGenerics, spaceInsideParens, strongOutlets, strongifiedSelf, todos
--disable acronyms, fileHeader, isEmpty, extensionAccessControl, redundantReturn, sortDeclarations, genericExtensions, redundantRawValues, redundantReturn, sortedSwitchCases, wrapConditionalBodies, wrapenumcases, wrapMultilineStatementBraces, wrapSingleLineComments, wrapSwitchCases, markTypes, organizeDeclarations
```

### PR DESCRIPTION
**Pull request by calda**
This PR fixes an issue where the `enumNamespaces` rule wouldn't be applied to a type following an import statement. Fixes #1569.

### CODE REVIEW

File: Sources/Rules.swift [hunk 1]
```diff
@@ -954,9 +954,8 @@ public struct _FormatRules {
             .keyword("class"),
             .keyword("struct"),
         ].contains($0) }) { i, token in
-            guard formatter.last(.keyword, before: i) != .keyword("import"),
```
Comment (calda) [inline Sources/Rules.swift:957]: I imagine this condition had something to do with cases like `import struct CurrencyFormatter`. There are tests cases that include code like this, and all of them still pass after making this change.

**Comment by nicklockwood** [comment]
Thank you!
