### PR TITLE
Fix issue where `--beforemarks` unexpectedly checked function bodies for matching keywords

### LINKED ISSUE #1907: organizeDeclarations bug
I'm using SwiftFormat with Cursor so that formatting is applied on save and this revealed an issue with the `organizeDeclarations` rule. When I edit functions with different access controls they will be grouped under the pragma mark comments correct and then I'll make some edits to a function and it will be ungrouped

I've attached a video demonstrating the issue:
https://github.com/user-attachments/assets/abf118de-09ad-4467-a1df-b2a1ee974f82

Here is my `.swiftformat` file:

```
--acronyms ID,URL,UUID
--allman false
--assetliterals visual-width
--beforemarks class,enum,let,struct,typealias,var
--binarygrouping 4,8
--categorymark "MARK: - %c -"
--classthreshold 0
--closingparen balanced
--closurevoid remove
--commas always
--conflictmarkers reject
--decimalgrouping 3,8
--elseposition same-line
--emptybraces no-space
--enumnamespaces always
--enumthreshold 0
--exponentcase lowercase
--exponentgrouping disabled
--extensionacl on-extension
--extensionlength 0
--extensionmark "MARK: - %t + %c"
--fractiongrouping disabled
--fragment false
--funcattributes prev-line
--generictypes 
--groupedextension "MARK: %c"
--guardelse auto
--hexgrouping 4,8
--hexliteralcase uppercase
--ifdef indent
--importgrouping testable-last
--indent 4
--indentcase false
--indentstrings false
--lifecycle layoutSubviews,loadView,viewDidAppear,viewDidDisappear,viewDidLoad,viewWillDisappear,willWillAppear
--lineaftermarks true
--linebreaks lf
--markcategories true
--markextensions always
--marktypes always
--maxwidth 120
--modifierorder override,public,private,lazy,weak,final,convenience
--nevertrailing 
--nospaceoperators 
--nowrapoperators <,>
--octalgrouping 4,8
--operatorfunc no-space
--organizetypes actor,class,enum,struct
--patternlet hoist
--ranges spaced
--redundanttype inferred
--self init-only
--selfrequired 
--semicolons never
--shortoptionals always
--smarttabs enabled
--someAny true
--stripunusedargs closure-only
--structthreshold 0
--tabwidth unspecified
--trailingclosures 
--trimwhitespace always
--typeattributes prev-line
--typeblanklines remove
--typemark "MARK: - %t"
--varattributes same-line
--voidtype void
--wraparguments before-first
--wrapcollections before-first
--wrapconditions preserve
--wrapparameters before-first
--wrapreturntype preserve
--wrapternary default
--wraptypealiases disabled
--xcodeindentation disabled
--yodaswap always
--disable strongOutlets,wrapMultilineStatementBraces
--enable blankLineAfterImports,blankLinesBetweenImports,blockComments,organizeDeclarations,wrapEnumCases,wrapSwitchCases

```

This of course is very irritating and causes a headache in code review as functions are shifted around causing large diffing changes.

This has been reproduced on the latest version `0.54.6`.

### PR DESCRIPTION
**Pull request by calda**
This PR fixes #1907.

`--beforemarks` was unexpectedly checking function bodies for matching keywords, so in this example with `--beforemarks var,let` the `someInternalFunction` declaration was unexpectedly being included in `beforeMarks` (because its body contained the `let` keyword):

```swift
public final class Test: ObservableObject {
    var someProperty: Int? = 0

    func someInternalFunction() {
        guard let someProperty: Int else {
            return
        }

        print("Hello")
        print("Hello")
        print("Hello")
        print("Hello")
        print("Hello")
    }
  
    // MARK: - Public -

    public func somePublicFunction() {
        print("Hello")
        print("Hello")
        print("Hello")
        print("Hello")
        print("Hello")
    }

    // MARK: - Private -

    private func somePrivateFunction() {
        print("Hello")
        print("Hello")
    }
}
```

### CODE REVIEW

File: Sources/DeclarationHelpers.swift [hunk 1]
```diff
@@ -555,10 +555,6 @@ extension Declaration {
                 return .beforeMarks
             }
 
-            for token in declarationParser.tokens {
-                if beforeMarks.contains(token.string) { return .beforeMarks }
```
Comment (calda) [inline Sources/DeclarationHelpers.swift:559]: Not sure what this check was for, all of the tests still pass without it. If somebody was relying on this for something we can consider how to support their desired behavior in a more reasonable way.

@oiuhr, I see you added this check in #1678. Do you remember why you added it?
