### PR TITLE
Fix issue where `redundantStaticSelf` rule could treat instance method as static method

### LINKED ISSUE #1446: `redundantStaticSelf` rule breaks build
I noticed the new `redundantStaticSelf` rule on `develop`, which looks great (nice work @sjavora). I ran this new rule on our codebase and found that it removes `Self` in many cases where it isn't actually redundant, breaking the build. 

Here's one example:

```swift
public enum MyFeatureCacheStrategy {
  case networkOnly
  case cacheFirst

  public static let defaultCacheAge: TimeInterval = .minutes(5)

  public func requestStrategy<Outcome>() -> SingleRequestStrategy<Outcome> {
    switch self {
    case .networkOnly:
      return .networkOnly(writeResultToCache: true)
    case .cacheFirst:
      // `Self.` is unexpectedly removed, breaking the build
      return .cacheFirst(maxCacheAge: Self.defaultCacheAge)
    }
  }
}
```

I left a comment about this on the implementation here: https://github.com/nicklockwood/SwiftFormat/pull/1437/files#r1187656440

### PR DESCRIPTION
**Pull request by calda**
This PR fixes #1446, where the `redundantStaticSelf` rule could unexpectedly treat an instance method as a static method, breaking the build.

### CODE REVIEW

File: Sources/Rules.swift [hunk 1]
```diff
@@ -3236,15 +3236,19 @@ public struct _FormatRules {
 
     /// Remove redundant Self keyword
     public let redundantStaticSelf = FormatRule(
-        help: "Remove explicit `Self` where applicable.",
-        disabledByDefault: true
```
Comment (calda) [inline Sources/Rules.swift:3240]: While we're here, how about we enable this by default

I imagine this rule wouldn't be controversial, since it's just like `redundantSelf` which is already enabled by default. If we find too many more issues with the implementation we could go back to having it disabled.
