### PR TITLE
Fix `parseGenericTypes` handling of constraints with their own generic types (e.g. `== Foo<Bar>`)

### LINKED ISSUE #1281: genericExtensions doesn't support nested generics
Thanks for such quick support of the new Swift 5.7 features.
Playing with it I've found this bug with `genericExtensions` option.

Here is an example of unformatted code:
```
extension Array where Element == Foo<Bar> {}
```

SwiftFormat produces this code with an error:
```
extension Array < Foo<Bar> {}
```

Tested on `0.50.1` and the latest develop 95c3702d0fd8415706099ec2a9acabd8092285fe

### PR DESCRIPTION
**Pull request by calda**
This PR fixes #1281, which affected both `opaqueGenericParameters` and `genericExtensions`.

This specific bug was originally fixed in https://github.com/nicklockwood/SwiftFormat/pull/1260, but it looks like the fix was lost at some point (probably due to merge conflicts?)

### CODE REVIEW

File: Tests/RulesTests+Syntax.swift [hunk 1]
```diff
@@ -3072,6 +3097,161 @@ class SyntaxTests: RulesTests {
         testFormatting(for: input, output, rule: FormatRules.genericExtensions, options: options)
     }
 
+    func testOpaqueGenericParametersRuleSuccessfullyTerminatesInSampleCode() {
```
Comment (calda) [inline Tests/RulesTests+Syntax.swift:3100]: I noticed the test cases from https://github.com/nicklockwood/SwiftFormat/pull/1260 were no longer included on develop, so I added them back. Some of them were failing on develop due to the bug fixed in this PR. Must have been lost in a merge conflict at some point when rearranging the git history of the develop branch?

Comment (nicklockwood) [reply Tests/RulesTests+Syntax.swift:3100]: Yeah, there was a conflict because I didn't rebase develop on master after release, Sorry about that.

Comment (calda) [reply Tests/RulesTests+Syntax.swift:3100]: All good, easy fix 👍🏻
